config/routes.rb
Facturacion::Application.routes.draw do

  resources :taxes

  resources :line_items

  resources :invoices

  resources :items

  resources :contacts

  resources :organizations

  require 'subdomain'
  constraints(Subdomain) do
    match '/' => 'sessions#new'
  end

  get 'logout' => 'sessions#destroy'
  get 'login' => "sessions#new"
  get 'signup' => "accounts#new"
  get 'dashboard' => "dashboard#index"
  root :to => 'accounts#new'
  resources :users
  resources :sessions

  resources :companies
  resources :accounts

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :account
  has_many :contacts, :dependent => :destroy
  has_many :invoices
  accepts_nested_attributes_for :contacts
  accepts_nested_attributes_for :invoices
  validates :account_id, :presence => true
  validates :name, :uniqueness => true
  
  def formatted_address
    a = "#{name} <br />" unless name.empty?
    a = "#{a} #{address_one} <br />" unless address_one.empty?
    a = "#{a} #{address_two} <br />" unless address_two.empty?
    a = "#{a} #{city} " unless self.city.empty?
    a = "#{a} #{state} " unless state.empty?
    a = "#{a} #{zipcode} <br />" unless zipcode.empty?
    a = "#{a} #{business_phone} <br />" unless business_phone.empty?
    a = "#{a} #{fax} <br />" unless fax.empty?
    a = "#{a} #{website}" unless website.empty?
    a
  end  
  
  # before_save :default_values
  # def default_values
  #   self.account_id = current_user.account_id
  # end
  
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  load_and_authorize_resource
  def index
    # @organizations = Organization.all
    respond_to do |format|
      format.html
    end
  end

  def show
    # @organization = Organization.find(params[:id])
    @contacts = @organization.contacts
    respond_to do |format|
      format.html
    end
  end

  def new
    @organization = Organization.new
    @organization.contacts.build
    respond_to do |format|
      format.html
    end
  end

  def edit
    # @organization = Organization.find(params[:id])
  end

  def create
    # @organization = Organization.new(params[:organization])
    @organization.contacts[0].account_id = current_user.account_id
    @organization.account_id = current_user.account_id if @organization.new_record?
    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    # @organization = Organization.find(params[:id])
    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    # @organization = Organization.find(params[:id])
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Organization</h2>

  <div class="field">
    <%= f.label :name, 'Organization name' %><br />
    <%= f.text_field :name %>
  </div>
  
  <h2>Contacts</h2>
  <%= f.fields_for :contacts do |contact_f| %>
  <div class="field">
      <%= contact_f.label :email %><br />
      <%= contact_f.text_field :email %>
  </div>
  
  <div class="field">
      <%= contact_f.label :first_name %><br />
      <%= contact_f.text_field :first_name %>
  </div>
  
  <div class="field">
      <%= contact_f.label :last_name %><br />
      <%= contact_f.text_field :last_name %>
  </div>
    
  <div class="field">
      <%= contact_f.label :mobile_phone %><br />
      <%= contact_f.text_field :mobile_phone %>
  </div>
  
  <div class="field">
      <%= contact_f.label :work_phone %><br />
      <%= contact_f.text_field :work_phone %>
  </div>

  <div class="field">
      <%= contact_f.label :home_phone %><br />
      <%= contact_f.text_field :home_phone %>
  </div>
  <% end %>
  
  <h2>Details</h2>
  
  <div class="field">
    <%= f.label :address_one %><br />
    <%= f.text_field :address_one %>
  </div>
  <div class="field">
    <%= f.label :address_two %><br />
    <%= f.text_field :address_two %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :business_phone %><br />
    <%= f.text_field :business_phone %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :disable_with => "Processing..." %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Clients</h1>

<%= link_to 'New Client', new_organization_url %>

<table class="listing">
  <tr>
    <th>ID</th>
    <th>Organization</th>
    <th>Contact</th>
    <th>Email</th>
    <th>Business Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.contacts[0].id %></td>
    <td><%= link_to organization.name, organization_url(organization) %></td>
    <td><%= organization.contacts[0].full_name %></td>
    <td><%= organization.contacts[0].email %></td>
    <td><%= organization.business_phone %></td>
    <td><%= link_to 'Show', organization %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td><%= link_to 'Destroy', organization, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<h1><%= @organization.name %></h1>

<p>
  Address:<br />
  <%= @organization.address_one %>
  <%= @organization.address_two %><br />
  <%= @organization.city %>  <%= @organization.state %> <%= @organization.zipcode %>
</p>

<p>
  Business phone: <%= @organization.business_phone %><br />
  Fax: <%= @organization.fax %>
  Website: <%= @organization.website %>
</p>

<% @contacts.each do |contact| %>
<p>
<b><%= contact.full_name %></b><br />
Email: <%= contact.email %><br />
Mobile: <%= contact.mobile_phone %><br />
Home: <%= contact.home_phone %><br />
Work: <%= contact.work_phone %>
</p>
<% end %>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>