config/routes.rb
Facturacion::Application.routes.draw do

  resources :taxes

  resources :line_items

  resources :invoices

  resources :items

  resources :contacts

  resources :organizations

  require 'subdomain'
  constraints(Subdomain) do
    match '/' => 'sessions#new'
  end

  get 'logout' => 'sessions#destroy'
  get 'login' => "sessions#new"
  get 'signup' => "accounts#new"
  get 'dashboard' => "dashboard#index"
  root :to => 'accounts#new'
  resources :users
  resources :sessions

  resources :companies
  resources :accounts

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facturacion</title>
  <%= stylesheet_link_tag    "admin" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">

<%= debug current_user %>

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", logout_path %>
  <% else %>
    <%= link_to "Sign up", signup_path %> or
    <%= link_to "log in", login_path %>
  <% end %>
</div>

<ul id="nav">
  <li><%= link_to 'Clients', organizations_url %></li>
  <li><%= link_to 'Invoices', invoices_url %></li>
  <li><%= link_to 'Items', items_url %></li>
  <li><%= link_to 'Taxes', taxes_url %></li>
  <li><%= link_to 'My Info', user_url(current_user)  %></li>
</ul>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<div id="content">
<%= yield %>
</div><!-- content -->

</div> <!-- wrapper -->

</body>
</html>

app/views/layouts/admin_code.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facturacion</title>
  <%= stylesheet_link_tag    "admin" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", logout_path %>
  <% else %>
    <%= link_to "Sign up", signup_path %> or
    <%= link_to "log in", login_path %>
  <% end %>
</div>

<ul id="nav">
  <li><%= link_to 'Clients', organizations_url %></li>
  <li><%= link_to 'Invoices', invoices_url %></li>
  <li><%= link_to 'Items', items_url %></li>
  <li><%= link_to 'Taxes', taxes_url %></li>
  <li><%= link_to 'My Info', user_url(current_user)  %></li>
</ul>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<div id="content">
<%= yield %>
</div><!-- content -->

</div> <!-- wrapper -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facturacion</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", logout_path %>
  <% else %>
    <%= link_to "Sign up", signup_path %> or
    <%= link_to "log in", login_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>